### ISSUE TITLE
Publishing Theme error

### ISSUE THREAD

**Issue by jcfilben** [grommet/grommet-theme-designer#9]
Moved this issue from grommet to here
https://github.com/grommet/grommet/issues/4476

> **Expected Behavior**
>To publish theme
>
>**Actual Behavior**
>Form validation error even when fulfilled

![image](https://user-images.githubusercontent.com/54560994/92972791-1b389a00-f440-11ea-8559-ebdf47a74ae1.png)

**Comment by ericsoderberghp** [comment]
Fixed in 5c0dffbdc83444a46640abf3fe351e4e8243a931

**Comment by ericsoderberghp** [comment]
Apologies @mjftw, I hadn't seen your pull request until after pushing a fix for this.
